name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      pages: write
      id-token: write

    env:
      PUBLIC_URL: ./

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Build
      run: |
        npm install
        npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: build

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2